config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  root 'welcome#index'

  resources :histories

  get 'histories/getPrices/:symbol' => 'histories#getPrices'

end

app/models/history.rb
class History < ActiveRecord::Base
      validates :symbol, presence: true, length: { minimum: 3 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/histories_controller.rb
class HistoriesController < ApplicationController
   def show
      @history = History.find( params[:id] )
   end

   def index
      @histories = History.all
   end

   def new
      @history = History.new
   end

   def create_check
      render plain: params[:history][:symbol].inspect
   end

   def create
      @histories = History.new(history_params)
      @histories.save

      redirect_to @histories
   end

   #
   # assumes one price entry per day.

   def getPrices
      @prices = History.where(:symbol => params[:symbol]).last(30).map {|x| x.price}
      render json: @prices
   end

   private
      def history_params
         params.require(:history).permit(:symbol, :price)
      end
end

app/controllers/prices_controller.rb
class PricesController < ApplicationController
   def new
   end

   def create
       render plain: params[:history].inspect
   end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/helpers/history_helper.rb
module HistoryHelper
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/histories/index.html.erb
<h1>Known Data</h1>
 
<%= link_to 'New', new_history_path %>

<table>
  <tr>
    <th>Symbol</th>
  </tr>
 
  <% @histories.each do |history| %>
    <tr>
      <td><%= history.symbol %></td>
    </tr>
  <% end %>
</table>

app/views/histories/new.html.erb
<h2> Enter Symbol and Price </h1>


<% if @history.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@history.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @history.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


<%= form_for :history, url: histories_path do |f| %>
  <p>
    <%= f.label :symbol %><br>
    <%= f.text_field :symbol %>
  </p>
 
  <p>
    <%= f.label :price %><br>
    <%= f.number_field :price, :step => "0.01" %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/histories/show.html.erb
<p>
  <strong>Stock Symbol:</strong>
  <%= @history.symbol %>
</p>
 
<p>
  <strong>Price:</strong>
  <%= @history.price %>
</p>
 
<%= link_to 'Back', histories_path %>

app/views/histories/view.html.erb
<p>
  <strong>Symoble:</strong>
  <%= @history.symbol %>
</p>
 
<p>
  <strong>Price:</strong>
  <%= @history.price %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pricehistory</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/prices/new.html.erb
<h2> Enter Symbol and Price </h1>

<%= form_for :price do |f| %>
  <p>
    <%= f.label :symbol %><br>
    <%= f.text_field :symbol %>
  </p>
 
  <p>
    <%= f.label :price %><br>
    <%= f.text_area :float %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/welcome/index.html.erb
<head>
   <%= javascript_include_tag('plotly-latest.min.js') %>
   <script>

     function range(start,end,inc) {
        var arr = [];
        for (var i = start; i <= end; i += inc) {
          arr.push(i);
        }
        return arr;
     }

     function dograph(symbol) {

        var x = range(0,29,1)

        $.ajax({
             type: "GET",
             url: "/histories/getPrices/" + symbol,
             dataType: "json",
             success: function(data){
                 GRAPH = document.getElementById('graph');
                 Plotly.plot( GRAPH, [{ x: x, y: data  }], 
                                  { margin: { t: 0 } } );
             }        
        });

     }


   </script>
</head>

<body>
   <center><h2> Stock prices for last 30 days</h2></center>
   <form action="" onsubmit="return dograph()">
   <select name="aa" onchange="dograph(this.value)">
      <option value="">Chose a stock</option>
      <option value="ORCL">Oracle</option>
      <option value="AAPL">Apple</option>
      <option value="MSFT">Microsoft</option>
      <option value="BMW">BMW</option>
   </select>`
   </form>
   <div id="graph" style="width:600px;height:250px;"></div>
</body>